//
//  SplashPresenter.swift
//  MoonCodeTemplate
//
//  Created by Komsit Chusangthong on 8/7/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
	func presentSomething(response: Splash.Something.Response)
}

class SplashPresenter: SplashPresentationLogic {
	weak var viewController: SplashDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: Splash.Something.Response) {
		let viewModel = Splash.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}


