//
//  SplashWorker.swift
//  MoonCodeTemplate
//
//  Created by Komsit Chusangthong on 8/7/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SplashWorkerable {
    func getExampleObject(id: String) async throws -> Result<ExampleResponse, Error>
}

final class SplashWorker: SplashWorkerable {
    private let getExampleObjectUsecase: GetExampleObjectUsecase!
    
    init(getExampleObjectUsecase: GetExampleObjectUsecase? = GetExampleObjectUsecaseImpl()) {
        self.getExampleObjectUsecase = getExampleObjectUsecase
    }
    
    func getExampleObject(id: String) async throws -> Result<ExampleResponse, Error> {
        return try await getExampleObjectUsecase.execute(id: id)
    }
}

